version: "3.9"
services:
  postgres:
    image: postgres:14.8
    environment:
      POSTGRES_DB: "wb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
    ports:
      - "5432:5432"

  nats-streaming:
    # command:
    # - nats-streaming
    container_name: nats-streaming
    image: nats-streaming
    ports:
    - 4222:4222
    - 8222:8222
